decouple blog from scripts

diff --git a/blog-template b/blog-template
--- a/blog-template
+++ b/blog-template
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+yell() { echo ": $*" >&2; }
+die () { yell "$*"; exit 111; }
+try () { "$@" || die "cannot $*" ; }
+
 print_usage () {
 cat << EOF
     Usage:  ${0##*/} [-t <template.html>] [-h <header.html>] <file.html>
@@ -27,6 +31,14 @@ headfilename=""
 
 bodyfilename=""
 
+checkfile () {
+	if [ -f $1 ] ; then
+		return 0
+	else
+		return 1
+	fi
+}
+
 for arg in ${*}; do
     if [ "$arg" = "-t" ] ; then
         template_=1
@@ -34,18 +46,21 @@ for arg in ${*}; do
         headfile_=1
     elif [ "$template_" = "1" ] ; then
         template=$arg
+		try checkfile $arg
         template_=2
     elif [ "$headfile_" = "1" ] ; then
         headfilename=$arg
+		try checkfile $arg
         headfile_=2
     else
         bodyfilename=$arg
+		try checkfile $arg
     fi
 done
 
 if [ "$template_" = "0" ] ; then
 
-template=$(mktemp)
+template=`mktemp`
 cat > $template << EOF
 <!DOCTYPE HTML>
 <html>
@@ -75,9 +90,9 @@ body{
 p {
 	text-align: justify;
 	text-justify: inter-word;}
-h3.list-link {
+.index-link {
      line-height: 40%;}
-h6.list-date {
+.list-date {
 	line-height: 20%;}
 </style>
 
